# Generated by Django 5.2.16 on 2026-07-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_permit_no', models.CharField(max_length=255, unique=True)),
                ('contact_no', models.CharField(max_length=11, unique=True)),
                ('description', models.TextField()),
                ('company_logo', models.ImageField(upload_to='company_logo')),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
