# Generated by Django 5.2.16 on 2026-07-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='category',
        ),
    ]
