# Generated by Django 5.2.16 on 2026-07-20 06:03

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_jobpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(
                default=timezone.now,
            ),
            preserve_default=False,
        ),
    ]