# Generated by Django 5.2.16 on 2026-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_employer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
