# Generated by Django 5.2.16 on 2026-08-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_jobapplication_cover_letter_jobapplication_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
