# Generated by Django 5.2.16 on 2026-08-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_jobapplication_cover_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/cover_letters/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(default=14.069444444444445, upload_to='company_logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
