# Generated by Django 5.2.16 on 2026-09-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_jobapplication_cover_letter_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('business_permit_no', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=11)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
