# Generated by Django 5.2.16 on 2026-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantRegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=266)),
                ('last_name', models.CharField(max_length=266)),
                ('middle_name', models.CharField(max_length=266)),
                ('password', models.CharField(max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover/')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
