# Generated by Django 5.2.16 on 2026-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_applicantregistrationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter skills separated by commas. Example: Python, Django, React, SQL', null=True),
        ),
    ]
