# Generated by Django 5.2.16 on 2026-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_applicant_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantregistrationotp',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
